// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqdUqwtZ23FuPetbnq_Kv0PgwdYYObICc',
    appId: '1:517541915143:web:e8b6fbe6aae35b4cac98a2',
    messagingSenderId: '517541915143',
    projectId: 'book-store-193be',
    authDomain: 'book-store-193be.firebaseapp.com',
    storageBucket: 'book-store-193be.appspot.com',
    measurementId: 'G-J7M7869SFD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2VE8MlgWsbJH6yupseS71xw4e0FmU2mU',
    appId: '1:517541915143:android:ec126361492d9f7bac98a2',
    messagingSenderId: '517541915143',
    projectId: 'book-store-193be',
    storageBucket: 'book-store-193be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM4hPzPEwk9HRJBv7NVYcfyTzwheN-1GQ',
    appId: '1:517541915143:ios:5ce972177ab615f6ac98a2',
    messagingSenderId: '517541915143',
    projectId: 'book-store-193be',
    storageBucket: 'book-store-193be.appspot.com',
    iosClientId: '517541915143-l2ussukf56fgis9riqs4t6pru432hmoh.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBM4hPzPEwk9HRJBv7NVYcfyTzwheN-1GQ',
    appId: '1:517541915143:ios:6130206359ec6d2dac98a2',
    messagingSenderId: '517541915143',
    projectId: 'book-store-193be',
    storageBucket: 'book-store-193be.appspot.com',
    iosClientId: '517541915143-bdelgpen57e7ikm5e5suki9lp15gl8vk.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookStore.RunnerTests',
  );
}
